### ISSUE TITLE
members - date d'inscription

### ISSUE THREAD

**Issue by lilian-benoit** [BordeauxJUG/bdxjug-api#1]
Il serait intéressant que le service retourne aussi la date d'inscription des membres.
Nous avons l'information dans la colonne date de la 1er inscription.

**Comment by binout** [comment]
C'est fait.

Ajout du champ "firstRegistration" :
  {
    "firstName": "Jean",
    "lastName": "Dupont",
    "endOfValidity": {
      "year": 2018,
      "month": 9,
      "day": 23
    },
    "**firstRegistration**": {
      "year": 2014,
      "month": 9,
      "day": 23
    }
  },
