### ISSUE TITLE
speakers - twitter account

### ISSUE THREAD

**Issue by lilian-benoit** [BordeauxJUG/bdxjug-api#2]
Les speakers communiquent beaucoup avec les réseaux sociaux dont twitter.
Il serait intéressant de rajouter l'information sur un compte twitter

Ensuite, nous mettrons à jour les données au fur et à mesure.

**Comment by binout** [comment]
C'est fait.

Ajout du champ "twitter" dans speaker si rempli dans la spreadsheet.
